### ISSUE TITLE
The day of the month is not showing, due to the lack of the percent signal "%" 

### ISSUE THREAD

**Issue by felipendc** [BradHeff/hefftor-polybar#1]
https://github.com/BradHeff/hefftor-polybar/blob/e076081b62fbb1242cb3301bae900528d94e5d62/.config/polybar/config#L611

The day was being printed: -d-02-2020 instead of 02-02-2020

The wrong one:
date-alt = "d-%m-%Y"

The correct one:
date-alt = "%d-%m-%Y"

**Comment by BradHeff** [comment]
thanks for noticing. will fix it and push an update.

thanks mate.

**Comment by felipendc** [comment]
No problem. :)

**Comment by BradHeff** [comment]
done :)
